### ISSUE TITLE
One result per line

### ISSUE THREAD

**Issue by Evidlo** [Granitosaurus/parsel-cli#3]
I've been enjoying parsel as a quick way to scrape links from websites. One thing I've been missing is a way to get results separated by newline.

For example, how would I modify this command to get one link per line?

    parsel -p absolute -x '//a/@href' http://example.com

**Comment by Granitosaurus** [comment]
Sorry for a very late response but I just got back to maintaining this package. In the new v1.0.0 (release WIP) you can use `--join-with \n` processor:

```
$ parsel -x '//a/@href' -i "--absolute --join-with \n" http://github.com
# or shortform
$ parsel -x '//a/@href' -i "-aJc \n" http://github.com
https://github.com/#start-of-content
https://docs.github.com/articles/supported-browsers
https://github.com/
....
```
In shell form it would look like:

```
$ poetry run parsel http://github.com
> --absolute --join-with \n
default processors: [AbsoluteUrl, Join('\n')]  
> //a/@href
https://github.com/#start-of-content
https://docs.github.com/articles/supported-browsers
https://github.com/
```

**Comment by Granitosaurus** [comment]
Closing this as v1.0.0 was released and contains this new feature.
